// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUfC9tpsbk2dH_8TTzZoFvx27XGq3WS9o',
    appId: '1:424148821778:web:398f38ba4be51b03d1f5cb',
    messagingSenderId: '424148821778',
    projectId: 'mealsetu-786',
    authDomain: 'mealsetu-786.firebaseapp.com',
    storageBucket: 'mealsetu-786.firebasestorage.app',
    measurementId: 'G-EVVJZTME0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr_2YLYKhq7nUZoVqMegsIuVz4e2TrWxg',
    appId: '1:424148821778:android:e62c9add806b002bd1f5cb',
    messagingSenderId: '424148821778',
    projectId: 'mealsetu-786',
    storageBucket: 'mealsetu-786.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh9vu6vd2CGPA7UwlAvfMX21snRlT4moc',
    appId: '1:424148821778:ios:2587098f77a01403d1f5cb',
    messagingSenderId: '424148821778',
    projectId: 'mealsetu-786',
    storageBucket: 'mealsetu-786.firebasestorage.app',
    iosBundleId: 'com.mealsetu.mealsetuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh9vu6vd2CGPA7UwlAvfMX21snRlT4moc',
    appId: '1:424148821778:ios:2587098f77a01403d1f5cb',
    messagingSenderId: '424148821778',
    projectId: 'mealsetu-786',
    storageBucket: 'mealsetu-786.firebasestorage.app',
    iosBundleId: 'com.mealsetu.mealsetuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUfC9tpsbk2dH_8TTzZoFvx27XGq3WS9o',
    appId: '1:424148821778:web:25d92d67d60d3be3d1f5cb',
    messagingSenderId: '424148821778',
    projectId: 'mealsetu-786',
    authDomain: 'mealsetu-786.firebaseapp.com',
    storageBucket: 'mealsetu-786.firebasestorage.app',
    measurementId: 'G-Q7K4DXVYLV',
  );
}
